Category.find_or_create_by(name: "Work")
Category.find_or_create_by(name: "Life")
Category.find_or_create_by(name: "Hobby")
Category.find_or_create_by(name: "Other")
Category.find_or_create_by(name: "Programing")